{% set name = "dolfinx_mpc" %}
{% set version = "0.8.0" %}
{% set major_minor = version.rsplit(".", 1)[0] %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/jorgensd/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4c77ce49b28b04974205f62dc04d5324168f8d2275f6ee4d7fa24aa4e0ac2eaa

build:
  number: 0
  skip: true  # [win or py<39]

  # openmpi oversubscribe env
  script_env:
    - OMPI_ALLOW_RUN_AS_ROOT=1
    - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - OMPI_MCA_rmaps_base_oversubscribe=1
    - OMPI_MCA_plm=isolated
    - OMPI_MCA_btl=vader,self
    - OMPI_MCA_btl_vader_single_copy_mechanism=none
    - MPIEXEC_TIMEOUT=120

outputs:
  - name: libdolfinx_mpc
    script: build-cpp.sh
    build:
      run_exports:
        - {{ pin_subpackage("libdolfinx_mpc", max_pin="x.x") }}
      force_use_keys:
        - python

    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - make
        - pkg-config
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - fenics-libdolfinx {{ major_minor }}
        - fenics-libbasix {{ major_minor }}
        - fenics-ufcx {{ major_minor }}
        - {{ mpi }}
        - petsc
        - petsc * {{ scalar }}_*
      run:
        - fenics-libdolfinx
        - fenics-libbasix
        - {{ mpi }}
        - petsc
    test:
      commands:
        - test -f $PREFIX/lib/libdolfinx_mpc${SHLIB_EXT}

  - name: dolfinx_mpc
    script: build-py.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python  # [build_platform != target_platform]
        - nanobind  # [build_platform != target_platform]
      host:
        - {{ pin_subpackage("libdolfinx_mpc", exact=True) }}
        - fenics-libbasix {{ major_minor }}
        - fenics-basix {{ major_minor }}
        - fenics-libdolfinx {{ major_minor }}
        - fenics-dolfinx {{ major_minor }}
        - {{ mpi }}
        - petsc
        - petsc * {{ scalar }}_*
        - pip
        - python
        - scikit-build-core
        - nanobind
      run:
        - {{ pin_subpackage("libdolfinx_mpc", exact=True) }}
        - fenics-basix
        - fenics-dolfinx
        - {{ mpi }}
        - numpy >=1.21
        - python
      run_constrained:
        - {{ pin_compatible("nanobind", "x.x") }}

    test:
      source_files:
        - python/tests
      requires:
        - pip
        - pytest
        - pytest-asyncio
        - python-gmsh
        - scipy
      commands:
        - pytest -vs python/tests
        - mpirun -n 2 pytest python/tests
        - pip check

about:
  home: https://github.com/jorgensd/dolfinx_mpc
  summary: Multi-point constraints with FEniCS-X
  description: |
    This library contains an add-on to FEniCSx enabling the possibilities of enforce multi-point constraints
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://jorgensd.github.io/dolfinx_mpc
  dev_url: https://github.com/jorgensd/dolfinx_mpc

extra:
  feedstock-name: dolfinx_mpc
  recipe-maintainers:
    - jorgensd
    - minrk
