{% set name = "dolfinx_mpc" %}
{% set version = "0.6.1" %}
{% set major_minor = version.rsplit(".", 1)[0] %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/jorgensd/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ec001621be3b4b7122d8b8e889b60c11a246827f88703778b428beb644c08fbb

build:
  number: 0
  skip: true  # [win]

outputs:
  - name: libdolfinx_mpc
    script: build-cpp.sh
    build:
      run_exports:
        - {{ pin_subpackage("libdolfinx_mpc", max_pin="x.x") }}

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - fenics-libdolfinx {{ major_minor }}
        - fenics-libbasix {{ major_minor }}
        - fenics-ufcx {{ major_minor }}
        - {{ mpi }}
        - petsc
      run:
        - fenics-libdolfinx
        - fenics-libbasix
        - {{ mpi }}
        - petsc
    test:
      commands:
        - test -f $PREFIX/lib/libdolfinx_mpc${SHLIB_EXT}

  - name: dolfinx_mpc
    script: build-py.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - {{ pin_subpackage("libdolfinx_mpc", exact=True) }}
        - fenics-libbasix {{ major_minor }}
        - fenics-basix {{ major_minor }}
        - fenics-libdolfinx {{ major_minor }}
        - fenics-dolfinx {{ major_minor }}
        - {{ mpi }}
        - petsc
        - pip
        - python
        - pybind11
      run:
        - {{ pin_subpackage("libdolfinx_mpc", exact=True) }}
        - fenics-basix
        - fenics-dolfinx
        - {{ mpi }}
        - numpy >=1.21
        - python

    test:
      source_files:
        - python/tests
      requires:
        - pip
        - pytest
        - pytest-asyncio
        - python-gmsh
        - scipy
      commands:
        - pytest -vs python/tests
        - mpirun -n 2 pytest python/tests
        - pip check

about:
  home: https://github.com/jorgensd/dolfinx_mpc
  summary: Multi-point constraints with FEniCS-X
  description: |
    This library contains an add-on to FEniCSx enabling the possibilities of enforce multi-point constraints
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://jorgensd.github.io/dolfinx_mpc
  dev_url: https://github.com/jorgensd/dolfinx_mpc

extra:
  feedstock-name: dolfinx_mpc
  recipe-maintainers:
    - jorgensd
    - minrk
